# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather_notification.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'weather_notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aweather_notification.proto\x12\x14weather_notification\"\"\n\x0eWeatherRequest\x12\x10\n\x08location\x18\x01 \x01(\t\"6\n\x0fWeatherResponse\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x11\n\tcondition\x18\x02 \x01(\t\"&\n\x13NotificationRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x14NotificationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2k\n\x0eWeatherService\x12Y\n\nGetWeather\x12$.weather_notification.WeatherRequest\x1a%.weather_notification.WeatherResponse2\x80\x01\n\x13NotificationService\x12i\n\x10SendNotification\x12).weather_notification.NotificationRequest\x1a*.weather_notification.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERREQUEST']._serialized_start=52
  _globals['_WEATHERREQUEST']._serialized_end=86
  _globals['_WEATHERRESPONSE']._serialized_start=88
  _globals['_WEATHERRESPONSE']._serialized_end=142
  _globals['_NOTIFICATIONREQUEST']._serialized_start=144
  _globals['_NOTIFICATIONREQUEST']._serialized_end=182
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=184
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=222
  _globals['_WEATHERSERVICE']._serialized_start=224
  _globals['_WEATHERSERVICE']._serialized_end=331
  _globals['_NOTIFICATIONSERVICE']._serialized_start=334
  _globals['_NOTIFICATIONSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
